/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v3/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain access token
         * @description Exchange credentials for an access token. This is the OAuth 2.0 token endpoint.
         *
         *     **Supported Grant Types:**
         *
         *     - `authorization_code`: Exchange an authorization code for an access token
         *     - `authorization_code` + PKCE: For public clients without a client secret
         *     - `client_credentials`: Authenticate as your application (server-to-server)
         *
         *     **PKCE Support:** For public clients (mobile apps, SPAs), use PKCE by sending
         *     `code_challenge` and `code_challenge_method` in the authorization request, then
         *     include `code_verifier` when exchanging the code. See [RFC 7636](https://tools.ietf.org/html/rfc7636).
         *
         *     Access tokens do not expire and can be used indefinitely. Register your application
         *     at [are.na/oauth/applications](https://www.are.na/oauth/applications) to obtain client credentials.
         */
        post: operations["createOAuthToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/openapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get OpenAPI specification
         * @description Returns the OpenAPI 3.0 specification for this API in YAML format. This endpoint provides the complete API contract for programmatic access and documentation generation.
         */
        get: operations["getOpenapiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get OpenAPI specification (JSON)
         * @description Returns the OpenAPI 3.0 specification for this API in JSON format. This endpoint provides the complete API contract in JSON for tools that prefer JSON over YAML.
         */
        get: operations["getOpenapiSpecJson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping endpoint
         * @description Public utility endpoint for API health checks and connection testing.
         */
        get: operations["getPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/blocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a block
         * @description Returns detailed information about a specific block by its ID. Respects visibility rules and user permissions.
         */
        get: operations["getBlock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/blocks/{id}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get block connections
         * @description Returns paginated list of channels where this block appears.
         *     This shows all channels that contain this block, respecting visibility rules and user permissions.
         */
        get: operations["getBlockConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/blocks/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get block comments
         * @description Returns paginated list of comments on this block.
         *     Comments are ordered by creation date (ascending by default, oldest first).
         */
        get: operations["getBlockComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a channel
         * @description Returns detailed information about a specific channel by its ID or slug. Respects visibility rules and user permissions.
         */
        get: operations["getChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/channels/{id}/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get channel contents
         * @description Returns paginated contents (blocks and channels) from a channel.
         *     Respects visibility rules and user permissions.
         */
        get: operations["getChannelContents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/channels/{id}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get channel connections
         * @description Returns paginated list of channels where this channel appears.
         *     This shows all channels that contain this channel, respecting visibility rules and user permissions.
         */
        get: operations["getChannelConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/channels/{id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get channel followers
         * @description Returns paginated list of users who follow this channel.
         *     All followers are users.
         */
        get: operations["getChannelFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the currently authenticated user's profile
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user
         * @description Returns detailed information about a specific user by their slug. Includes user profile, bio, and counts.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/users/{id}/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user contents
         * @description Returns paginated contents (blocks and channels) created by a user.
         *     Uses the search API to find all content added by the specified user.
         *     Respects visibility rules and user permissions.
         */
        get: operations["getUserContents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/users/{id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user followers
         * @description Returns paginated list of users who follow this user.
         *     All followers are users.
         */
        get: operations["getUserFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/users/{id}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user following
         * @description Returns paginated list of users, channels, and groups that this user follows.
         *     Can be filtered by type to return only specific followable types.
         */
        get: operations["getUserFollowing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a group
         * @description Returns detailed information about a specific group by its slug. Includes group profile, bio, owner, and counts.
         */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/groups/{id}/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get group contents
         * @description Returns paginated contents (blocks and channels) created by a group.
         *     Uses the search API to find all content added by the specified group.
         *     Respects visibility rules and user permissions.
         */
        get: operations["getGroupContents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/groups/{id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get group followers
         * @description Returns paginated list of users who follow this group.
         *     All followers are users.
         */
        get: operations["getGroupFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search across Are.na
         * @description Search across blocks, channels, users, and groups.
         *
         *     **⚠️ Premium Only**: This endpoint requires a Premium subscription.
         *
         *     **Examples:**
         *     - Simple: `/v3/search?q=brutalism`
         *     - Images only: `/v3/search?q=architecture&type=Image`
         *     - My content: `/v3/search?q=*&scope=my`
         *     - In a channel: `/v3/search?q=design&scope=channel:12345`
         *     - PDFs sorted by date: `/v3/search?q=*&ext=pdf&sort=created_at_desc`
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Error message
             * @example Not Found
             */
            error: string;
            /**
             * @description HTTP status code
             * @example 404
             */
            code: number;
            /** @description Additional error details */
            details?: {
                /**
                 * @description Detailed error message
                 * @example The resource you are looking for does not exist.
                 */
                message?: string;
            };
        };
        /** @description Rate limit exceeded error response with upgrade information and suggestions */
        RateLimitError: {
            error: {
                /**
                 * @description Error type identifier
                 * @example rate_limit_exceeded
                 */
                type: string;
                /**
                 * @description Human-readable error message
                 * @example Rate limit of 30 requests per minute exceeded for guest tier. Try again later.
                 */
                message: string;
                /**
                 * @description User's current tier
                 * @example guest
                 * @enum {string}
                 */
                tier: "guest" | "free" | "premium" | "supporter";
                /**
                 * @description Request limit per minute for this tier
                 * @example 30
                 */
                limit: number;
                /**
                 * @description Time window for rate limits
                 * @example 1 minute
                 */
                limit_window?: string;
                /**
                 * @description Suggested seconds to wait before retrying
                 * @example 65
                 */
                retry_after: number;
                current_status?: {
                    /** @example guest */
                    tier?: string;
                    /**
                     * @example {
                     *       "guest": 30,
                     *       "free": 120,
                     *       "premium": 300,
                     *       "supporter": 600
                     *     }
                     */
                    limits?: Record<string, never>;
                    upgrade_path?: {
                        /** @example Guest (30 req/min) */
                        current?: string;
                        /** @example Free Account (120 req/min) */
                        recommended?: string;
                        /**
                         * @example [
                         *       "4x higher rate limit",
                         *       "Persistent authentication",
                         *       "API access"
                         *     ]
                         */
                        benefits?: string[];
                        /** @example Sign up at https://are.na/signup */
                        action?: string;
                    };
                };
                /**
                 * @description Tier-specific optimization suggestions
                 * @example [
                 *       "Sign up for a free account to get 120 requests per minute",
                 *       "Implement exponential backoff with jitter",
                 *       "Cache responses when possible to reduce API calls",
                 *       "Consider batch requests if available"
                 *     ]
                 */
                suggestions: string[];
                /**
                 * @description Information about header usage
                 * @example Check 'X-RateLimit-*' headers on successful requests for current usage
                 */
                headers_note?: string;
            };
        };
        /**
         * @description HATEOAS links for navigation and discovery.
         *     Follows HAL (Hypertext Application Language) format where link relationships
         *     are expressed as object keys (e.g., "self", "user", "channels").
         */
        Links: {
            self: components["schemas"]["Link"] & unknown;
        } & {
            [key: string]: components["schemas"]["Link"];
        };
        /**
         * @description A hypermedia link containing the URL of a linked resource.
         *     The relationship type is expressed by the key in the parent _links object.
         */
        Link: {
            /**
             * Format: uri
             * @description The URL of the linked resource
             * @example https://api.are.na/v3/blocks/12345
             */
            href: string;
        };
        /** @description Markdown content with multiple renderings */
        MarkdownContent: {
            /**
             * @description Original markdown value
             * @example This is **only** a [test](https://example.com).
             */
            markdown: string;
            /**
             * @description HTML rendering of the markdown
             * @example <p>This is <strong>only</strong> a <a href="https://example.com" target="_blank" rel="nofollow noopener">test</a>.</p>
             */
            html: string;
            /**
             * @description Plain text rendering of the markdown
             * @example This is only a test (https://example.com).
             */
            plain: string;
        };
        /** @description Embedded user representation (used when user is nested in other resources) */
        EmbeddedUser: {
            /**
             * @description Unique identifier for the user
             * @example 12345
             */
            id: number;
            /**
             * @description User type (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "User";
            /**
             * @description User's display name
             * @example John Doe
             */
            name: string;
            /**
             * @description URL-safe identifier (use this in API paths)
             * @example john-doe
             */
            slug: string;
            /**
             * Format: uri
             * @description URL to user's avatar image
             * @example https://d2w9rnfcy7mm78.cloudfront.net/12345/avatar.jpg
             */
            avatar: string | null;
            /**
             * @description User's initials
             * @example JD
             */
            initials: string;
        };
        /**
         * @description Connection metadata that describes how an item is connected to a channel.
         *     This is only present when the item is returned as part of a channel's contents.
         */
        ConnectionContext: {
            /**
             * @description Unique identifier for the connection
             * @example 98765
             */
            id: number;
            /**
             * @description Position of the item within the channel (for manual ordering)
             * @example 1
             */
            position: number;
            /**
             * @description Whether the item is pinned to the top of the channel
             * @example false
             */
            pinned: boolean;
            /**
             * Format: date-time
             * @description When the item was connected to the channel
             * @example 2023-01-15T10:30:00Z
             */
            connected_at: string;
            /** @description User who connected this item to the channel */
            connected_by: components["schemas"]["EmbeddedUser"] | null;
        };
        /** @description Embedded group representation (used when group is nested in other resources) */
        EmbeddedGroup: {
            /**
             * @description Unique identifier for the group
             * @example 67890
             */
            id: number;
            /**
             * @description Group type (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "Group";
            /**
             * @description Group's name
             * @example Design Team
             */
            name: string;
            /**
             * @description Group's URL slug
             * @example design-team-abc123
             */
            slug: string;
            /**
             * Format: uri
             * @description URL to group's avatar image
             * @example https://d2w9rnfcy7mm78.cloudfront.net/groups/67890/avatar.jpg
             */
            avatar: string | null;
            /**
             * @description Group's initials
             * @example DT
             */
            initials: string;
        };
        /** @description Full user representation */
        User: components["schemas"]["EmbeddedUser"] & {
            /**
             * Format: date-time
             * @description When the user was created
             * @example 2023-01-15T10:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the user was last updated
             * @example 2023-06-20T14:45:00Z
             */
            updated_at: string;
            /** @description User biography with markdown, HTML, and plain text renderings */
            bio?: components["schemas"]["MarkdownContent"] | null;
            counts: components["schemas"]["UserCounts"];
            _links: components["schemas"]["Links"] & unknown;
        };
        /** @description Counts of various items for the user */
        UserCounts: {
            /**
             * @description Number of channels owned by the user
             * @example 24
             */
            channels: number;
            /**
             * @description Number of followers
             * @example 156
             */
            followers: number;
            /**
             * @description Number of users being followed
             * @example 89
             */
            following: number;
        };
        /** @description Full group representation */
        Group: components["schemas"]["EmbeddedGroup"] & {
            /** @description Group biography with markdown, HTML, and plain text renderings */
            bio?: components["schemas"]["MarkdownContent"] | null;
            /**
             * Format: date-time
             * @description When the group was created
             * @example 2023-01-15T10:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the group was last updated
             * @example 2023-06-20T14:45:00Z
             */
            updated_at: string;
            user: components["schemas"]["EmbeddedUser"] & unknown;
            counts: components["schemas"]["GroupCounts"];
            _links: components["schemas"]["Links"] & unknown;
        };
        /** @description Counts of various items for the group */
        GroupCounts: {
            /**
             * @description Number of channels owned by the group
             * @example 12
             */
            channels: number;
            /**
             * @description Number of users in the group
             * @example 5
             */
            users: number;
        };
        /**
         * @description Filter for content types (blocks and channels)
         * @enum {string}
         */
        ContentTypeFilter: "Text" | "Image" | "Link" | "Attachment" | "Embed" | "Channel" | "Block";
        /**
         * @description Filter for searchable content types (includes all content types plus users and groups)
         * @enum {string}
         */
        SearchTypeFilter: "All" | "Text" | "Image" | "Link" | "Attachment" | "Embed" | "Channel" | "Block" | "User" | "Group";
        /**
         * @description Supported file extensions for filtering
         * @enum {string}
         */
        FileExtension: "aac" | "ai" | "aiff" | "avi" | "avif" | "bmp" | "csv" | "doc" | "docx" | "eps" | "epub" | "fla" | "gif" | "h264" | "heic" | "heif" | "ind" | "indd" | "jpeg" | "jpg" | "key" | "kml" | "kmz" | "latex" | "m4a" | "ma" | "mb" | "mid" | "midi" | "mov" | "mp3" | "mp4" | "mp4v" | "mpeg" | "mpg" | "mpg4" | "numbers" | "oga" | "ogg" | "ogv" | "otf" | "pages" | "pdf" | "pgp" | "png" | "ppt" | "pptx" | "psd" | "svg" | "swa" | "swf" | "tex" | "texi" | "texinfo" | "tfm" | "tif" | "tiff" | "torrent" | "ttc" | "ttf" | "txt" | "wav" | "webm" | "webp" | "wma" | "xls" | "xlsx" | "xlt";
        /**
         * @description Sort order for connection lists (channels containing a block/channel, followers)
         * @enum {string}
         */
        ConnectionSort: "created_at_desc" | "created_at_asc";
        /**
         * @description Sort order for channel contents (includes position for manual ordering)
         * @enum {string}
         */
        ChannelContentSort: "position_asc" | "position_desc" | "created_at_asc" | "created_at_desc" | "updated_at_asc" | "updated_at_desc";
        /**
         * @description Sort order for user/group content lists
         * @enum {string}
         */
        ContentSort: "created_at_asc" | "created_at_desc" | "updated_at_asc" | "updated_at_desc";
        /**
         * @description A block is a piece of content on Are.na. Blocks come in different types,
         *     each with its own set of fields. Use the `type` field to determine which
         *     fields are available.
         */
        Block: components["schemas"]["TextBlock"] | components["schemas"]["ImageBlock"] | components["schemas"]["LinkBlock"] | components["schemas"]["AttachmentBlock"] | components["schemas"]["EmbedBlock"];
        /** @description Common properties shared by all block types */
        BaseBlockProperties: {
            /**
             * @description Unique identifier for the block
             * @example 12345
             */
            id: number;
            /**
             * @description Base type of the block (always "Block")
             * @example Block
             * @enum {string}
             */
            base_type: "Block";
            /**
             * @description Block title
             * @example Interesting Article
             */
            title?: string | null;
            /** @description Block description with multiple renderings */
            description?: components["schemas"]["MarkdownContent"] | null;
            /**
             * @description Processing state of the block:
             *     - `available`: Block is ready and fully processed
             *     - `pending`: Block is queued for processing
             *     - `processing`: Block is currently being processed (e.g., image thumbnails, metadata extraction)
             *     - `failed`: Block processing failed (may still be viewable but incomplete)
             * @example available
             * @enum {string}
             */
            state: "available" | "pending" | "failed" | "processing";
            /**
             * @description Visibility level of the block:
             *     - `public`: Visible to everyone
             *     - `private`: Only visible to the owner
             *     - `orphan`: Block exists but is not connected to any channel
             * @example public
             * @enum {string}
             */
            visibility: "public" | "private" | "orphan";
            /**
             * @description Number of comments on the block
             * @example 5
             */
            comment_count: number;
            /**
             * Format: date-time
             * @description When the block was created
             * @example 2023-01-15T10:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the block was last updated
             * @example 2023-01-15T14:45:00Z
             */
            updated_at: string;
            user: components["schemas"]["EmbeddedUser"];
            /** @description Source URL and metadata (if block was created from a URL) */
            source?: components["schemas"]["BlockSource"] | null;
            _links: components["schemas"]["Links"] & unknown;
            /**
             * @description Connection context (only present when block is returned as part of channel contents).
             *     Contains position, pinned status, and information about who connected the block.
             */
            connection?: components["schemas"]["ConnectionContext"] | null;
        };
        /** @description A text block containing markdown content */
        TextBlock: components["schemas"]["BaseBlockProperties"] & {
            /**
             * @description Block type (always "Text" for TextBlock)
             * @enum {string}
             */
            type: "Text";
            /** @description Text content with markdown, HTML, and plain text renderings */
            content: components["schemas"]["MarkdownContent"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Text";
        };
        /** @description An image block containing an uploaded or scraped image */
        ImageBlock: components["schemas"]["BaseBlockProperties"] & {
            /**
             * @description Block type (always "Image" for ImageBlock)
             * @enum {string}
             */
            type: "Image";
            /** @description Image data with multiple resolutions */
            image: components["schemas"]["BlockImage"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Image";
        };
        /** @description A link block representing a URL with optional preview */
        LinkBlock: components["schemas"]["BaseBlockProperties"] & {
            /**
             * @description Block type (always "Link" for LinkBlock)
             * @enum {string}
             */
            type: "Link";
            /** @description Preview image (if available) */
            image?: components["schemas"]["BlockImage"] | null;
            /** @description Extracted text content from the link */
            content?: components["schemas"]["MarkdownContent"] | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Link";
        };
        /** @description An attachment block containing an uploaded file */
        AttachmentBlock: components["schemas"]["BaseBlockProperties"] & {
            /**
             * @description Block type (always "Attachment" for AttachmentBlock)
             * @enum {string}
             */
            type: "Attachment";
            /** @description Attachment file data */
            attachment: components["schemas"]["BlockAttachment"];
            /** @description Preview image (for PDFs and other previewable files) */
            image?: components["schemas"]["BlockImage"] | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Attachment";
        };
        /** @description An embed block containing embedded media (video, audio, etc.) */
        EmbedBlock: components["schemas"]["BaseBlockProperties"] & {
            /**
             * @description Block type (always "Embed" for EmbedBlock)
             * @enum {string}
             */
            type: "Embed";
            /** @description Embed data including HTML and dimensions */
            embed: components["schemas"]["BlockEmbed"];
            /** @description Thumbnail image (if available) */
            image?: components["schemas"]["BlockImage"] | null;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Embed";
        };
        BlockSource: {
            /**
             * Format: uri
             * @description Source URL
             * @example https://example.com/article
             */
            url: string;
            /**
             * @description Source title
             * @example Original Article Title
             */
            title?: string | null;
            provider?: components["schemas"]["BlockProvider"] | null;
        };
        BlockProvider: {
            /**
             * @description Provider name (from parsed URI host)
             * @example Example.com
             */
            name: string;
            /**
             * Format: uri
             * @description Provider URL (from parsed URI scheme and host)
             * @example https://example.com
             */
            url: string;
        };
        BlockImage: {
            /**
             * @description Alternative text associated with the image
             * @example Scanned collage of magazine cutouts
             */
            alt_text?: string | null;
            /**
             * @description BlurHash representation of the image for progressive loading
             * @example LEHV6nWB2yk8pyo0adR*.7kCMdnj
             */
            blurhash?: string | null;
            /**
             * @description Original image width in pixels
             * @example 1920
             */
            width?: number | null;
            /**
             * @description Original image height in pixels
             * @example 1080
             */
            height?: number | null;
            /**
             * Format: float
             * @description Image aspect ratio (width / height)
             * @example 1.7778
             */
            aspect_ratio?: number | null;
            /**
             * @description Image content type
             * @example image/jpeg
             */
            content_type?: string;
            /**
             * @description Image filename
             * @example image.jpg
             */
            filename?: string;
            /**
             * @description File size in bytes
             * @example 1024000
             */
            file_size?: number | null;
            /**
             * Format: date-time
             * @description When the image was last updated
             * @example 2023-01-15T14:45:00Z
             */
            updated_at?: string;
            small: components["schemas"]["ImageVersion"] & unknown;
            medium: components["schemas"]["ImageVersion"] & unknown;
            large: components["schemas"]["ImageVersion"] & unknown;
            square: components["schemas"]["ImageVersion"] & unknown;
        };
        /** @description A resized/processed version of an image with multiple resolution URLs */
        ImageVersion: {
            /**
             * Format: uri
             * @description Default image URL (1x resolution)
             * @example https://d2w9rnfcy7mm78.cloudfront.net/12345/display_image.jpg
             */
            src: string;
            /**
             * Format: uri
             * @description 1x resolution image URL
             * @example https://d2w9rnfcy7mm78.cloudfront.net/12345/display_image.jpg
             */
            src_1x: string;
            /**
             * Format: uri
             * @description 2x resolution image URL for high DPI displays
             * @example https://d2w9rnfcy7mm78.cloudfront.net/12345/display_image@2x.jpg
             */
            src_2x: string;
            /**
             * Format: uri
             * @description 3x resolution image URL for very high DPI displays
             * @example https://d2w9rnfcy7mm78.cloudfront.net/12345/display_image@3x.jpg
             */
            src_3x: string;
            /**
             * @description Width of the resized image in pixels
             * @example 640
             */
            width?: number | null;
            /**
             * @description Height of the resized image in pixels
             * @example 480
             */
            height?: number | null;
        };
        BlockEmbed: {
            /**
             * Format: uri
             * @description Embed URL
             * @example https://www.youtube.com/embed/abc123
             */
            url?: string | null;
            /**
             * @description Embed type
             * @example youtube
             */
            type?: string | null;
            /**
             * @description Embed title
             * @example Video Title
             */
            title?: string | null;
            /**
             * @description Author name
             * @example Author Name
             */
            author_name?: string | null;
            /**
             * Format: uri
             * @description Author URL
             * @example https://example.com/author
             */
            author_url?: string | null;
            /**
             * Format: uri
             * @description Embed source URL
             * @example https://www.youtube.com/watch?v=abc123
             */
            source_url?: string | null;
            /**
             * @description Embed width
             * @example 640
             */
            width?: number | null;
            /**
             * @description Embed height
             * @example 480
             */
            height?: number | null;
            /**
             * @description Embed HTML
             * @example <iframe src='...'></iframe>
             */
            html?: string | null;
            /**
             * Format: uri
             * @description Thumbnail URL
             * @example https://example.com/thumbnail.jpg
             */
            thumbnail_url?: string | null;
        };
        BlockAttachment: {
            /**
             * @description Attachment filename
             * @example document.pdf
             */
            filename?: string | null;
            /**
             * @description Attachment content type
             * @example application/pdf
             */
            content_type?: string | null;
            /**
             * @description File size in bytes
             * @example 2048000
             */
            file_size?: number | null;
            /**
             * @description File extension
             * @example pdf
             */
            file_extension?: string | null;
            /**
             * Format: date-time
             * @description When the attachment was last updated
             */
            updated_at?: string | null;
            /**
             * Format: uri
             * @description Attachment download URL
             * @example https://attachments.are.na/12345/document.pdf
             */
            url: string;
        };
        /** @description A comment on a block */
        Comment: {
            /**
             * @description Unique identifier for the comment
             * @example 12345
             */
            id: number;
            /**
             * @description Comment type
             * @example Comment
             * @enum {string}
             */
            type: "Comment";
            /** @description Comment body with markdown, HTML, and plain text renderings */
            body?: components["schemas"]["MarkdownContent"] | null;
            /**
             * Format: date-time
             * @description When the comment was created
             * @example 2023-01-15T10:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the comment was last updated
             * @example 2023-01-15T14:45:00Z
             */
            updated_at: string;
            user: components["schemas"]["EmbeddedUser"];
            _links: components["schemas"]["Links"] & unknown;
        };
        Channel: {
            /**
             * @description Unique identifier for the channel
             * @example 12345
             */
            id: number;
            /**
             * @description Channel type
             * @example Channel
             * @enum {string}
             */
            type: "Channel";
            /**
             * @description Channel URL slug
             * @example my-collection-abc123
             */
            slug: string;
            /**
             * @description Channel title
             * @example My Collection
             */
            title: string;
            /** @description Channel description with multiple renderings */
            description?: components["schemas"]["MarkdownContent"] | null;
            /**
             * @description Lifecycle state of the channel:
             *     - `available`: Channel is active and accessible
             *     - `deleted`: Channel has been soft-deleted
             * @example available
             * @enum {string}
             */
            state: "available" | "deleted";
            /**
             * @description Visibility level of the channel:
             *     - `public`: Anyone can view and connect to the channel
             *     - `private`: Only the owner and collaborators can view
             *     - `closed`: Anyone can view, but only collaborators can add content
             * @example public
             * @enum {string}
             */
            visibility: "public" | "private" | "closed";
            /**
             * Format: date-time
             * @description When the channel was created
             * @example 2023-01-15T10:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the channel was last updated
             * @example 2023-01-15T14:45:00Z
             */
            updated_at: string;
            owner: components["schemas"]["ChannelOwner"];
            counts: components["schemas"]["ChannelCounts"];
            _links: components["schemas"]["Links"] & unknown;
            /**
             * @description Connection context (only present when channel is returned as part of another channel's contents).
             *     Contains position, pinned status, and information about who connected the channel.
             */
            connection?: components["schemas"]["ConnectionContext"] | null;
        };
        /** @description Channel owner (User or Group) */
        ChannelOwner: components["schemas"]["EmbeddedUser"] | components["schemas"]["EmbeddedGroup"];
        /** @description Counts of various items in the channel */
        ChannelCounts: {
            /**
             * @description Number of blocks in the channel
             * @example 42
             */
            blocks: number;
            /**
             * @description Number of channels connected to this channel
             * @example 8
             */
            channels: number;
            /**
             * @description Total number of contents (blocks + channels)
             * @example 50
             */
            contents: number;
            /**
             * @description Number of collaborators on the channel
             * @example 3
             */
            collaborators: number;
        };
        /** @description Pagination metadata when total counts are available */
        PaginationMetaWithCount: {
            /**
             * @description Current page number
             * @example 1
             */
            current_page: number;
            /**
             * @description Next page number (null if last page)
             * @example 2
             */
            next_page?: number | null;
            /** @description Previous page number (null if first page) */
            prev_page?: number | null;
            /**
             * @description Number of items per page
             * @example 25
             */
            per_page: number;
            /**
             * @description Total number of pages available
             * @example 5
             */
            total_pages: number;
            /**
             * @description Total number of items available
             * @example 120
             */
            total_count: number;
            /**
             * @description Whether there are more pages available
             * @example true
             */
            has_more_pages: boolean;
        };
        /** @description Pagination metadata when total counts are not available */
        PaginationMetaWithoutCount: {
            /**
             * @description Current page number
             * @example 1
             */
            current_page: number;
            /**
             * @description Next page number (null if last page)
             * @example 2
             */
            next_page?: number | null;
            /** @description Previous page number (null if first page) */
            prev_page?: number | null;
            /**
             * @description Number of items per page
             * @example 25
             */
            per_page: number;
            /**
             * @description Whether there are more pages available
             * @example true
             */
            has_more_pages: boolean;
        };
        /** @description Pagination metadata union matching pagination behavior with and without total counts */
        PaginationMeta: components["schemas"]["PaginationMetaWithCount"] | components["schemas"]["PaginationMetaWithoutCount"];
        /** @description Base schema for all paginated responses (use allOf to extend with specific data type) */
        PaginatedResponseBase: {
            meta: components["schemas"]["PaginationMeta"];
        };
        /** @description Base schema for paginated responses with total count (use allOf to extend with specific data type) */
        PaginatedResponseWithCountBase: {
            meta: components["schemas"]["PaginationMetaWithCount"];
        };
        /** @description Data payload containing an array of users */
        UserList: {
            /** @description Array of users */
            data: components["schemas"]["User"][];
        };
        /** @description Data payload containing an array of channels */
        ChannelList: {
            /** @description Array of channels */
            data: components["schemas"]["Channel"][];
        };
        /** @description Data payload containing mixed content that can be connected to channels (blocks and channels) */
        ConnectableList: {
            /** @description Array of blocks and channels */
            data: (components["schemas"]["TextBlock"] | components["schemas"]["ImageBlock"] | components["schemas"]["LinkBlock"] | components["schemas"]["AttachmentBlock"] | components["schemas"]["EmbedBlock"] | components["schemas"]["Channel"])[];
        };
        /** @description Data payload containing followable items (users, channels, and groups) */
        FollowableList: {
            /** @description Array of users, channels, and/or groups */
            data: (components["schemas"]["User"] | components["schemas"]["Channel"] | components["schemas"]["Group"])[];
        };
        /** @description Data payload containing all content types */
        EverythingList: {
            /** @description Array of results (blocks, channels, users, or groups) */
            data: (components["schemas"]["TextBlock"] | components["schemas"]["ImageBlock"] | components["schemas"]["LinkBlock"] | components["schemas"]["AttachmentBlock"] | components["schemas"]["EmbedBlock"] | components["schemas"]["Channel"] | components["schemas"]["User"] | components["schemas"]["Group"])[];
        };
        /** @description Paginated list of users with total count */
        UserListResponse: components["schemas"]["UserList"] & components["schemas"]["PaginatedResponseWithCountBase"];
        /** @description Paginated list of channels with total count */
        ChannelListResponse: components["schemas"]["ChannelList"] & components["schemas"]["PaginatedResponseWithCountBase"];
        /** @description Paginated list of connectable content (blocks and channels) */
        ConnectableListResponse: components["schemas"]["ConnectableList"] & components["schemas"]["PaginatedResponseBase"];
        /** @description Paginated list of followable items (users, channels, and groups) with total count */
        FollowableListResponse: components["schemas"]["FollowableList"] & components["schemas"]["PaginatedResponseWithCountBase"];
        /** @description Paginated list of all content types with total count */
        EverythingListResponse: components["schemas"]["EverythingList"] & components["schemas"]["PaginatedResponseWithCountBase"];
        /** @description Data payload containing an array of comments */
        CommentList: {
            /** @description Array of comments */
            data: components["schemas"]["Comment"][];
        };
        /** @description Paginated list of comments with total count */
        CommentListResponse: components["schemas"]["CommentList"] & components["schemas"]["PaginatedResponseWithCountBase"];
        /** @description Health check response */
        PingResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
    };
    responses: {
        /** @description Unauthorized */
        UnauthorizedResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFoundResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation error */
        ValidationErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden - insufficient permissions to access this resource */
        ForbiddenResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimitResponse: {
            headers: {
                /**
                 * @description Seconds to wait before retrying
                 * @example 65
                 */
                "Retry-After"?: string;
                /**
                 * @description Request limit per minute
                 * @example 30
                 */
                "X-RateLimit-Limit"?: string;
                /**
                 * @description User's current tier
                 * @example guest
                 */
                "X-RateLimit-Tier"?: string;
                /**
                 * @description Time window in seconds
                 * @example 60
                 */
                "X-RateLimit-Window"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RateLimitError"];
            };
        };
    };
    parameters: {
        /**
         * @description Page number for pagination
         * @example 1
         */
        PageParam: number;
        /**
         * @description Number of items per page (max 100)
         * @example 24
         */
        PerParam: number;
        /** @description Resource ID */
        IdParam: number;
        /** @description Resource ID or slug */
        SlugOrIdParam: string;
        /**
         * @description Sort order (by created_at)
         * @example created_at_desc
         */
        ConnectionSortParam: components["schemas"]["ConnectionSort"];
        /**
         * @description Sort order for content lists
         * @example created_at_desc
         */
        ContentSortParam: components["schemas"]["ContentSort"];
        /**
         * @description Sort order for channel contents
         * @example position_asc
         */
        ChannelContentSortParam: components["schemas"]["ChannelContentSort"];
        /**
         * @description Filter by content type
         * @example Image
         */
        ContentTypeFilterParam: components["schemas"]["ContentTypeFilter"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createOAuthToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /**
                     * @description The OAuth 2.0 grant type
                     * @enum {string}
                     */
                    grant_type: "authorization_code" | "client_credentials";
                    /** @description Your application's client ID (required for all grant types) */
                    client_id?: string;
                    /** @description Your application's client secret (required for confidential clients, omit for PKCE) */
                    client_secret?: string;
                    /** @description Authorization code (required for authorization_code grant) */
                    code?: string;
                    /**
                     * Format: uri
                     * @description Redirect URI used in authorization request (required for authorization_code grant)
                     */
                    redirect_uri?: string;
                    /**
                     * @description PKCE code verifier (required when authorization used code_challenge).
                     *     Must be 43-128 characters from [A-Z], [a-z], [0-9], "-", ".", "_", "~".
                     */
                    code_verifier?: string;
                };
            };
        };
        responses: {
            /** @description Access token granted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "abc123def456...",
                     *       "token_type": "Bearer",
                     *       "scope": "write",
                     *       "created_at": 1702900000
                     *     }
                     */
                    "application/json": {
                        /** @description The access token to use for API requests */
                        access_token: string;
                        /**
                         * @description Token type (always "Bearer")
                         * @enum {string}
                         */
                        token_type: "Bearer";
                        /**
                         * @description Granted scopes (space-separated)
                         * @example write
                         */
                        scope: string;
                        /** @description Unix timestamp when the token was created */
                        created_at: number;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error?: "invalid_request" | "invalid_client" | "invalid_grant" | "unauthorized_client" | "unsupported_grant_type";
                        error_description?: string;
                    };
                };
            };
            /** @description Invalid client credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example invalid_client */
                        error?: string;
                        /** @example Client authentication failed due to unknown client or invalid credentials. */
                        error_description?: string;
                    };
                };
            };
        };
    };
    getOpenapiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI specification in YAML format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
            404: components["responses"]["NotFoundResponse"];
        };
    };
    getOpenapiSpecJson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI specification in JSON format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["NotFoundResponse"];
        };
    };
    getPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ping response */
            200: {
                headers: {
                    /**
                     * @description Request limit per minute for this user's tier
                     * @example 120
                     */
                    "X-RateLimit-Limit"?: string;
                    /**
                     * @description User's current tier
                     * @example free
                     */
                    "X-RateLimit-Tier"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getBlockConnections: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order (by created_at)
                 * @example created_at_desc
                 */
                sort?: components["parameters"]["ConnectionSortParam"];
                /**
                 * @description Filter connections by ownership:
                 *     - `ALL`: All accessible connections (default)
                 *     - `OWN`: Only connections created by the current user
                 *     - `EXCLUDE_OWN`: All connections except those created by the current user
                 * @example ALL
                 */
                filter?: "ALL" | "OWN" | "EXCLUDE_OWN";
            };
            header?: never;
            path: {
                /** @description Resource ID */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of channels where this block appears */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getBlockComments: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order (by created_at)
                 * @example created_at_desc
                 */
                sort?: components["parameters"]["ConnectionSortParam"];
            };
            header?: never;
            path: {
                /** @description Resource ID */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of comments on this block */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getChannelContents: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order for channel contents
                 * @example position_asc
                 */
                sort?: components["parameters"]["ChannelContentSortParam"];
                /**
                 * @description Filter by user who added the content
                 * @example 12345
                 */
                user_id?: number;
            };
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel contents with pagination metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectableListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getChannelConnections: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order (by created_at)
                 * @example created_at_desc
                 */
                sort?: components["parameters"]["ConnectionSortParam"];
            };
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of channels where this channel appears */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getChannelFollowers: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order (by created_at)
                 * @example created_at_desc
                 */
                sort?: components["parameters"]["ConnectionSortParam"];
            };
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users who follow this channel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getUserContents: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order for content lists
                 * @example created_at_desc
                 */
                sort?: components["parameters"]["ContentSortParam"];
                /**
                 * @description Filter by content type
                 * @example Image
                 */
                type?: components["parameters"]["ContentTypeFilterParam"];
            };
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User contents with pagination metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectableListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getUserFollowers: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order (by created_at)
                 * @example created_at_desc
                 */
                sort?: components["parameters"]["ConnectionSortParam"];
            };
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users who follow this user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getUserFollowing: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order (by created_at)
                 * @example created_at_desc
                 */
                sort?: components["parameters"]["ConnectionSortParam"];
                /**
                 * @description Filter by followable type
                 * @example Channel
                 */
                type?: "User" | "Channel" | "Group";
            };
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users, channels, and groups that this user follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowableListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getGroupContents: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order for content lists
                 * @example created_at_desc
                 */
                sort?: components["parameters"]["ContentSortParam"];
                /**
                 * @description Filter by content type
                 * @example Image
                 */
                type?: components["parameters"]["ContentTypeFilterParam"];
            };
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group contents with pagination metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectableListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    getGroupFollowers: {
        parameters: {
            query?: {
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
                /**
                 * @description Sort order (by created_at)
                 * @example created_at_desc
                 */
                sort?: components["parameters"]["ConnectionSortParam"];
            };
            header?: never;
            path: {
                /** @description Resource ID or slug */
                id: components["parameters"]["SlugOrIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users who follow this group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedResponse"];
            403: components["responses"]["ForbiddenResponse"];
            404: components["responses"]["NotFoundResponse"];
            429: components["responses"]["RateLimitResponse"];
        };
    };
    search: {
        parameters: {
            query?: {
                /**
                 * @description Search query. Use `*` to match everything (useful with filters).
                 * @example design
                 */
                q?: string;
                /**
                 * @description Content types to search (comma-separated).
                 *     Block subtypes: Text, Image, Link, Attachment, Embed.
                 *     Other: Channel, User, Group, Block (all block types).
                 * @example [
                 *       "Image",
                 *       "Link"
                 *     ]
                 */
                type?: components["schemas"]["SearchTypeFilter"][];
                /**
                 * @description Where to search:
                 *     - `all` - Everything (default)
                 *     - `my` - Current user's content
                 *     - `following` - Content from followed users/channels
                 *     - `user:ID` - Specific user's content
                 *     - `group:ID` - Specific group's content
                 *     - `channel:ID` - Specific channel's content
                 * @example channel:12345
                 */
                scope?: string;
                /**
                 * @description Fields to search within (comma-separated).
                 *     Options: name, description, content, domain, url.
                 *     Defaults to all fields.
                 * @example [
                 *       "name",
                 *       "description"
                 *     ]
                 */
                in?: ("name" | "description" | "content" | "domain" | "url")[];
                /**
                 * @description Filter by file extensions (comma-separated)
                 * @example [
                 *       "pdf",
                 *       "jpg"
                 *     ]
                 */
                ext?: components["schemas"]["FileExtension"][];
                /**
                 * @description Sort order. Options:
                 *     - `score_desc` (default) - Relevance
                 *     - `created_at_desc`, `created_at_asc`
                 *     - `updated_at_desc`, `updated_at_asc`
                 *     - `name_asc`, `name_desc`
                 *     - `connections_count_desc`
                 *     - `random` (use with `seed` for reproducibility)
                 * @example created_at_desc
                 */
                sort?: "score_desc" | "created_at_desc" | "created_at_asc" | "updated_at_desc" | "updated_at_asc" | "name_asc" | "name_desc" | "connections_count_desc" | "random";
                /**
                 * @description Only return results updated after this date (ISO 8601)
                 * @example 2024-01-01T00:00:00Z
                 */
                after?: string;
                /**
                 * @description Random seed for reproducible results (use with `sort=random`)
                 * @example 1234567890
                 */
                seed?: number;
                /**
                 * @description Page number for pagination
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Number of items per page (max 100)
                 * @example 24
                 */
                per?: components["parameters"]["PerParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results with pagination metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EverythingListResponse"];
                };
            };
            400: components["responses"]["ValidationErrorResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            /** @description Premium subscription required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Forbidden",
                     *       "code": 403,
                     *       "details": {
                     *         "message": "This endpoint requires a Premium subscription"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitResponse"];
        };
    };
}
